services:
  - type: web
    name: english-diary-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    disk:
      name: sqlite-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
